language: node_js
node_js: 
  - 13

services: 
  - docker

script: 
  - docker build -t user-api .
  - docker tag user-api emukungu/user-api:latest

after_success: 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push emukungu/user-api
